### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#209]
I'm going to publish my to-do list over here, so people can work on some stuff like that too. And feel free to add to it!
- [ ] del_player modes need to be handled all at once
- [ ] Reduce the clusterfuck that is transition_day and transition_night
- [ ] Modify !faftergame to allow multiple commands to be ran at once
- [ ] Dict of 'player: {totems they received}' to easily keep track (and apply them end of night) instead of a bunch of stupid variables
- [ ] Allow changing the default role to any arbitrary role
- [ ] Fix the "0-1 traitors" if only wolves could have killed
- [ ] Process stats procedurally
- [x] Send periodic pings to detect unclean exit
- [ ] Use git to be able to know which version one is on
- [ ] Make the account consistent everywhere - if it's ever '*', make it None, so 'if acc is None' can be used
- [ ] Make !frole call the same handlers that !start does to add new roles in (possibly new function)
- [ ] Make the logger more versatile (i.e. modifyable from config)
- [ ] Use mass_privmsg much more
- [x] Change everything to double-quoted where it makes sense to for consistency (maybe except role messages, since these use double-quotes inside the strings; to see)
- [x] Fix handle_error to use only the very first instance of it
- [ ] Praying succubus works even if you are entranced
- [x] Keep track of own nickname
- [ ] Get rid of var.OPPED and just use var.USERS[current_nick]["modes"]
- [ ] If a netsplit causes players to leave, possibly end game (or do something, at least, like not stasising the victims)

Anything else to add? If you can, edit this comment to add other stuff. If you can't, just comment and I can edit it myself.

**Comment by Diitto** [comment]
Maybe when there's an observed net split, the game ends?

**Comment by ChiyoOsaka** [comment]
I'd say to only end if it detects players in the game disconnecting because of a netsplit and not just random people.

**Comment by ishanyx** [comment]
Even then, say you have a 15p game going on and one player netsplits - the game shouldn't end for that, even if they don't reconnect.

**Comment by laneatomic** [comment]
It probably should be if the game detects a certain number of players suddenly leaving (probably due to netsplit but not necessarily).

**Comment by Vgr255** [comment]
Updated comment, thanks for the idea!

**Comment by jacob1** [comment]
I think it's better to let ops deal with it. Net splits are very unpredictable and canceling a game because a single person net split might be annoying. That person may have already noticed and reconnected but hasn't done !swap yet. Or maybe they already idled out because of the split a while ago (and in fact, most people will idle out before the *.net *.split comes in)

**Comment by skizzerz** [comment]
Closing since pretty much all of these are done. faftergame and the logger stuff are all that's left, and the logger stuff is tracked elsewhere.

Oh and netsplit detection but that's going to be hard to deal with and is tracked elsewhere as well.
